[package]
name = "vnq_server"
version = "0.2.1"
authors = ["Robert Usher <266585+dcchut@users.noreply.github.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.2", features = ["sqlite", "chrono"] }
dotenv = "0.14.1"
chrono = "0.4.7"
juniper = "0.13.1"
futures = "0.1"
actix-web = "1.0.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
actix-cors = "0.1.0"
actix-web-httpauth = "0.3.2"
jsonwebtoken = "6.0.1"